name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias
        run: dotnet restore MaquinaCafeTDD.slnx

      - name: Compilar proyecto
        run: dotnet build MaquinaCafeTDD.sln --configuration Release --no-restore

      - name: Ejecutar pruebas
        run: dotnet test MaquinaCafeTDD.sln --no-build --verbosity normal
